### ISSUE TITLE
Cannot run on `ubuntu-22.04`

### ISSUE THREAD

**Issue by allanlei** [docker/setup-buildx-action#146] opened 2022-05-12 03:12 UTC
Using `docker/setup-buildx-action@v2` on `ubuntu-22.04` will fail.  `ubuntu-20.04` is OK.

The changelog for docker doesn't seem like there was a change to docker

[ubuntu-20.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md)
```
Docker-Buildx 0.8.2
Docker-Moby Client 20.10.14+azure-1
Docker-Moby Server 20.10.14+azure-1
```

[ubuntu-22.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md)
```
Docker-Buildx 0.8.2
Docker-Moby Client 20.10.14+azure-1
Docker-Moby Server 20.10.14+azure-1
```

### Workflow

```yaml
name: Sample

on:
  push:

jobs:
  sample:
    runs-on: ubuntu-22.04
    steps:
    - uses: docker/setup-buildx-action@v2
```

### Results
```
Run docker/setup-buildx-action@v2
Docker info
  /usr/bin/docker version
  Client:
   Version:           20.10.14+azure-1
   API version:       1.41
   Go version:        go1.16.15
   Git commit:        a224086349269551becacce16e5842ceeb2a98d6
   Built:             Fri Mar  4 17:18:07 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Error: The process '/usr/bin/docker' failed with exit code 1
```

**Comment by crazy-max** [comment] 2022-05-12 03:48
> `ubuntu-22.04`

Don't think this image has been released yet: https://github.com/actions/virtual-environments#available-environments

**Comment by allanlei** [comment] 2022-05-12 16:54
Yes, this one is still in beta.

https://github.blog/changelog/2022-05-10-github-actions-beta-of-ubuntu-22-04-for-github-hosted-runners-is-now-available/

**Comment by crazy-max** [comment] 2022-05-16 23:18
Closing as the issue is not the action but the runner itself. Suggest to open an issue on https://github.com/actions/virtual-environments/ or wait for GA of this runner.

**Closed by crazy-max** 2022-05-16 23:18 UTC

**Comment by crazy-max** [comment] 2022-05-23 08:26
@allanlei Looks liek a cgroup issue, see https://github.com/actions/virtual-environments/issues/5490#issuecomment-1118328567
